// Generated by CoffeeScript 1.6.3
var MyClass;

module.exports = MyClass = (function() {
  function MyClass(title) {
    this.title = title;
  }

  MyClass.prototype.thing = function() {
    return 'Original Thing';
  };

  return MyClass;

})();
