// Generated by CoffeeScript 1.4.0
var SpecRun, Validator, specRun,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Validator = require('../validator');

SpecRun = (function(_super) {

  __extends(SpecRun, _super);

  function SpecRun() {
    return SpecRun.__super__.constructor.apply(this, arguments);
  }

  SpecRun.prototype.instance = function() {
    return {
      "class": 'ipso:SpecRun',
      version: 0
    };
  };

  SpecRun.prototype.protocol = function(When, Then) {};

  return SpecRun;

})(Validator);

if (typeof specRun === 'undefined') {
  specRun = new SpecRun;
}

module.exports = specRun;
