// Generated by CoffeeScript 1.6.3
var join, readFileSync, readdirSync, _ref;

_ref = require('fs'), readdirSync = _ref.readdirSync, readFileSync = _ref.readFileSync;

join = require('path').join;

module.exports = function(ipso) {
  return function(opts) {
    var aliases, compomnentsRoot, component, componentDir, componentFile, err, error, list, _i, _len, _ref1;
    compomnentsRoot = join(process.cwd(), 'components');
    try {
      list = {};
      aliases = {};
      _ref1 = readdirSync(compomnentsRoot);
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        componentDir = _ref1[_i];
        componentFile = join(compomnentsRoot, componentDir, 'component.json');
        try {
          component = JSON.parse(readFileSync(componentFile));
          list[component.name] = function() {};
          aliases[component.name] = join(compomnentsRoot, componentDir, component.main);
        } catch (_error) {
          error = _error;
          console.log("ipso: error loading component: " + componentFile);
        }
      }
    } catch (_error) {
      err = _error;
      switch (err.errno) {
        case 3:
          console.log("ipso: could not access directory: " + compomnentsRoot);
          break;
        case 34:
          console.log("ipso: expected directory: " + compomnentsRoot);
          break;
        default:
          console.log("ipso: unexpected error reading directory: " + compomnentsRoot);
      }
    }
    ipso.define(list, aliases);
    return ipso;
  };
};
