// Generated by CoffeeScript 1.6.3
var fs, path;

fs = require('fs');

path = require('path');

module.exports = function(ipso) {
  return function(opts) {
    var aliases, compomnentsRoot, component, componentDir, componentFile, err, error, injects, list, moduleName, tag, tags, _i, _len, _ref;
    ipso.does.mode('bridge');
    compomnentsRoot = path.join(process.cwd(), 'components');
    list = {};
    aliases = {};
    injects = {};
    try {
      _ref = fs.readdirSync(compomnentsRoot);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        componentDir = _ref[_i];
        componentFile = path.join(compomnentsRoot, componentDir, 'component.json');
        try {
          component = JSON.parse(fs.readFileSync(componentFile));
          list[component.name] = function() {};
          aliases[component.name] = path.join(compomnentsRoot, componentDir, component.main || 'index.js');
          if ((component.inject != null) && (component.inject.alias != null)) {
            injects[component.inject.alias] = component.name;
          }
        } catch (_error) {
          error = _error;
          console.log("ipso: error loading component: " + componentFile);
        }
      }
    } catch (_error) {
      err = _error;
      switch (err.errno) {
        case 3:
          console.log("ipso: could not access directory: " + compomnentsRoot);
          break;
        case 34:
          console.log("ipso: expected directory: " + compomnentsRoot);
          break;
        default:
          console.log("ipso: unexpected error reading directory: " + compomnentsRoot);
      }
    }
    ipso.define(list, {
      aliases: aliases
    });
    tags = {};
    for (tag in injects) {
      moduleName = injects[tag];
      tags[tag] = require(aliases[moduleName]);
    }
    ipso.tag(tags);
    return ipso;
  };
};
