// Generated by CoffeeScript 1.6.3
var fs, path;

fs = require('fs');

path = require('path');

module.exports = function(ipso) {
  return function(opts) {
    var aliases, compomnentsRoot, component, componentDir, componentFile, err, error, list, _i, _len, _ref;
    ipso.does.mode('bridge');
    compomnentsRoot = path.join(process.cwd(), 'components');
    try {
      list = {};
      aliases = {};
      _ref = fs.readdirSync(compomnentsRoot);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        componentDir = _ref[_i];
        componentFile = path.join(compomnentsRoot, componentDir, 'component.json');
        try {
          component = JSON.parse(fs.readFileSync(componentFile));
          list[component.name] = function() {};
          aliases[component.name] = path.join(compomnentsRoot, componentDir, component.main);
        } catch (_error) {
          error = _error;
          console.log("ipso: error loading component: " + componentFile);
        }
      }
    } catch (_error) {
      err = _error;
      switch (err.errno) {
        case 3:
          console.log("ipso: could not access directory: " + compomnentsRoot);
          break;
        case 34:
          console.log("ipso: expected directory: " + compomnentsRoot);
          break;
        default:
          console.log("ipso: unexpected error reading directory: " + compomnentsRoot);
      }
    }
    ipso.define(list, aliases);
    return ipso;
  };
};
