// Generated by CoffeeScript 1.6.3
var action, input, keypress, prompt, refresh, run, shutdown;

keypress = require('keypress');

keypress(process.stdin);

prompt = '> ';

input = '';

refresh = function() {
  process.stdout.clearLine();
  process.stdout.cursorTo(0);
  return process.stdout.write(prompt + input);
};

shutdown = function(code) {
  return process.exit(code);
};

action = function() {
  if (input !== '') {
    console.log({
      action: input
    });
  }
  return input = '';
};

run = function() {
  var stdin;
  stdin = process.openStdin();
  process.stdin.setRawMode(true);
  refresh();
  return process.stdin.on('keypress', function(chunk, key) {
    var ctrl, meta, name, sequence, shift;
    try {
      name = key.name, ctrl = key.ctrl, meta = key.meta, shift = key.shift, sequence = key.sequence;
    } catch (_error) {}
    if (ctrl && name === 'c') {
      return shutdown(0);
    }
    if (name === 'backspace') {
      input = input.slice(0, -1);
      return refresh();
    }
    if (name === 'return') {
      process.stdout.write('\n');
      action();
      process.stdout.write(prompt + input);
      return;
    }
    if (!chunk) {
      return;
    }
    input += chunk.toString();
    return refresh();
  });
};

run();
