// Generated by CoffeeScript 1.6.3
var normalize, spawn;

normalize = require('path').normalize;

spawn = require('child_process').spawn;

module.exports.inspector = function(opts, kids, refresh) {
  var arg1, arg2, arg3, bin, debugPort, kid, script, webPort, _ref;
  _ref = opts.args, arg1 = _ref[0], arg2 = _ref[1], arg3 = _ref[2];
  if (arg3 != null) {
    webPort = arg1;
    debugPort = arg2;
    script = arg3;
  } else if (arg2 != null) {
    webPort = arg1;
    debugPort = 5858;
    script = arg2;
  } else {
    webPort = 8080;
    debugPort = 5858;
    script = arg1;
  }
  console.log({
    webPort: webPort,
    debugPort: debugPort,
    script: script
  });
  bin = normalize(__dirname + '/../node_modules/.bin/node-inspector');
  kids.push(kid = spawn(bin, [
    "--web-port=" + (((function() {
      try {
        return parseInt(webPort);
      } catch (_error) {}
    })()) || 8080)
  ]));
  kid.stderr.on('data', function(chunk) {
    return refresh(chunk.toString(), 'stderr');
  });
  return kid.stdout.on('data', function(chunk) {
    var str;
    str = chunk.toString();
    str = str.replace(/5858/, debugPort);
    return refresh(str);
  });
};
