// Generated by CoffeeScript 1.6.3
var Mocha, MochaRunner;

Mocha = require('mocha');

module.exports = MochaRunner = (function() {
  function MochaRunner(reporter) {
    this.mocha = new Mocha({
      reporter: reporter
    });
  }

  MochaRunner.prototype.run = function(files, callback) {
    var file, _i, _len;
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      this.mocha.addFile(file);
    }
    return this.mocha.run(callback);
  };

  return MochaRunner;

})();
