// Generated by CoffeeScript 1.6.3
var Mocha, MochaRunner;

Mocha = require('mocha');

module.exports = MochaRunner = (function() {
  function MochaRunner(reporter) {
    this.mocha = new Mocha;
    reporter();
  }

  return MochaRunner;

})();
