// Generated by CoffeeScript 1.4.0
var exports;

exports = {
  necessity: function() {}
};

Object.defineProperty(Object.prototype, 'must', {
  get: function() {
    return exports.necessity;
  },
  set: function(value) {},
  enumerable: false
});

module.exports = exports;
