// Generated by CoffeeScript 1.4.0
var exports;

exports = {
  validatable: function() {}
};

Object.defineProperty(Object.prototype, 'receive', {
  get: function() {
    return exports.validatable;
  },
  set: function(value) {},
  enumerable: false
});

module.exports = exports;
