// Generated by CoffeeScript 1.4.0
var Validator;

module.exports = Validator = (function() {

  function Validator() {}

  Validator.prototype.configure = function(scaffold, opts) {
    return console.log('Validator.configure', arguments);
  };

  Validator.prototype.edge = function(placeholder, nodes) {
    return console.log('Validator.edge', arguments);
  };

  Validator.prototype.hup = function() {};

  Validator.prototype.handles = [];

  Validator.prototype.matches = [];

  return Validator;

})();
