// Generated by CoffeeScript 1.4.0
var Validator;

module.exports = Validator = (function() {

  function Validator() {}

  Validator.prototype.validate = function() {};

  Validator.prototype.configure = function(scaffold, opts) {};

  Validator.prototype.edge = function(placeholder, nodes) {};

  Validator.prototype.hup = function() {};

  Validator.prototype.handles = [];

  Validator.prototype.matches = [];

  return Validator;

})();
